import type { Metadata } from "next";
import localFont from 'next/font/local';

import "./globals.css";

const interFont = localFont({
  src: [
    { path: "./fonts/Inter-Regular.ttf", weight: "400"},
    { path: "./fonts/Inter-SemiBold.ttf", weight: "600"}
  ],
  variable: '--font-inter',

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={interFont.variable}>
      <body
        className={interFont.className}
      >
        {children}
      </body>
    </html>
  );
}
